server:
  port: 8090
spring:
  datasource:
    name: wallpaper
    url: jdbc:mysql://localhost:3306/wallpaper_db?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 10
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        min-idle: 10
        max-wait: 10000
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
#分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
file:
  path: file/**    #文件访问路径
  address:  D://wallpaper/  #文件保存路径


#redis